name: tableau-twilio
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26=hecd8cb5_2
  - certifi=2021.10.8=py39hecd8cb5_0
  - click=8.0.3=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - flask=2.0.2=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.0.2=pyhd3eb1b0_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - markupsafe=2.0.1=py39h9ed2024_0
  - ncurses=6.3=hca72f7f_2
  - openssl=1.1.1l=h9ed2024_0
  - pip=21.2.4=py39hecd8cb5_0
  - python=3.9.7=h88f2d9e_1
  - readline=8.1=h9ed2024_0
  - setuptools=58.0.4=py39hecd8cb5_0
  - sqlite=3.36.0=hce871da_0
  - tk=8.6.11=h7bc2e8c_0
  - tzdata=2021e=hda174b7_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/stephenlprice/anaconda3/envs/tableau-twilio
